version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: findbest_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pickai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: findbest_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRESQL_URL=postgresql+asyncpg://user:password@postgres:5432/pickai_db
    volumes:
      - .:/app
    command: python run.py

volumes:
  postgres_data:
